### ISSUE TITLE
GTEX  hg19 availability

### ISSUE THREAD

**Issue by marcDabad** [ChristopherWilks/snaptron#9]
Is there a possibility to change from GRCh38 to GRCh37(hg19) when we are querying GTEX?

**Comment by lcolladotor** [comment]
Hi @marcDabad,

I'm external to Snaptron, but I think that the answer is no.

That's because Snaptron is based on the Rail-RNA alignments that we used for creating recount2 https://www.nature.com/articles/nbt.3838 and those are hg38 based. Unless Chris lifted over exon-exon junctions from hg38 to hg19.

Best,
Leonardo

**Comment by ChristopherWilks** [comment]
Hi @marcDabad,

Leonardo is correct.  
All currently maintained Snaptron compilations (e.g. GTEx, TCGA, SRAv2) are on hg38.
We currently don't have any plans to make hg19 versions available.

For my own research I usually liftover query junctions, if they came from hg19, before searching them against Snaptron.
It's inconvenient but it usually works for the vast majority of them.

Chris
